import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`media\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`media_deleted_at_idx\` ON \`media\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`artists\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`artists_deleted_at_idx\` ON \`artists\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`_artists_v\` ADD \`version_deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`_artists_v_version_version_deleted_at_idx\` ON \`_artists_v\` (\`version_deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`exhibitions\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`exhibitions_deleted_at_idx\` ON \`exhibitions\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`_exhibitions_v\` ADD \`version_deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`_exhibitions_v_version_version_deleted_at_idx\` ON \`_exhibitions_v\` (\`version_deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`press\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`press_deleted_at_idx\` ON \`press\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`_press_v\` ADD \`version_deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`_press_v_version_version_deleted_at_idx\` ON \`_press_v\` (\`version_deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`events\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`events_deleted_at_idx\` ON \`events\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`_events_v\` ADD \`version_deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`_events_v_version_version_deleted_at_idx\` ON \`_events_v\` (\`version_deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`pages_deleted_at_idx\` ON \`pages\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`_pages_v_version_version_deleted_at_idx\` ON \`_pages_v\` (\`version_deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`viewing_rooms\` ADD \`deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`viewing_rooms_deleted_at_idx\` ON \`viewing_rooms\` (\`deleted_at\`);`)
  await db.run(sql`ALTER TABLE \`_viewing_rooms_v\` ADD \`version_deleted_at\` text;`)
  await db.run(sql`CREATE INDEX \`_viewing_rooms_v_version_version_deleted_at_idx\` ON \`_viewing_rooms_v\` (\`version_deleted_at\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`media_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`artists_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`artists\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`_artists_v_version_version_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`_artists_v\` DROP COLUMN \`version_deleted_at\`;`)
  await db.run(sql`DROP INDEX \`exhibitions_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`exhibitions\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`_exhibitions_v_version_version_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`_exhibitions_v\` DROP COLUMN \`version_deleted_at\`;`)
  await db.run(sql`DROP INDEX \`press_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`press\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`_press_v_version_version_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`_press_v\` DROP COLUMN \`version_deleted_at\`;`)
  await db.run(sql`DROP INDEX \`events_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`events\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`_events_v_version_version_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`_events_v\` DROP COLUMN \`version_deleted_at\`;`)
  await db.run(sql`DROP INDEX \`pages_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`_pages_v_version_version_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_deleted_at\`;`)
  await db.run(sql`DROP INDEX \`viewing_rooms_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`viewing_rooms\` DROP COLUMN \`deleted_at\`;`)
  await db.run(sql`DROP INDEX \`_viewing_rooms_v_version_version_deleted_at_idx\`;`)
  await db.run(sql`ALTER TABLE \`_viewing_rooms_v\` DROP COLUMN \`version_deleted_at\`;`)
}
